#!/bin/bash

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949248_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949248_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949248_2_trimmed.fastq



/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949249_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949249_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949249_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949250_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949250_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949250_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949251_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949251_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949251_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949252_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949252_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949252_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949253_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949253_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949253_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949254_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949254_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949254_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949255_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949255_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949255_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949256_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949256_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949256_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949257_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949257_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949257_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --limitBAMsortRAM 7039104133 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949258_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949258_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949258_2_trimmed.fastq

/opt/STAR/bin/Linux_x86_64/STAR --runThreadN 40 --limitBAMsortRAM 7039104133 --outFilterMultimapNmax -1 --genomeDir /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/index --outSAMattributes All --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/STARout/SRR949259_trimmed_almult --readFilesIn /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949259_1_trimmed.fastq /store/EQUIPES/PBI/Jonathan/Medicago_truncatula/FASTQpe/SRR949259_2_trimmed.fastq

